<?php

namespace Svenbw\LaravelTabler\Services;

use Carbon\Carbon;
use Carbon\Exceptions\InvalidFormatException;
use Illuminate\Support\Arr;

/**
 * Exposes the host application's build version to the Tabler views.
 *
 * The data is read from the application's `version` config, i.e. a
 * `config/version.php` in the host application. This package does not ship
 * that file: it is optional, and is typically generated by a build or deploy
 * step from the current git state. Every method degrades gracefully when the
 * config is absent, so the footer keeps rendering on a plain install.
 *
 * Expected shape:
 *
 *     // config/version.php
 *     return [
 *         'version' => 'v1.4.2',        // string, shown by @appVersion
 *         'dirty'   => false,           // bool, appends '-dirty' to the version
 *         'raw'     => 'v1.4.2-3-gab1c', // string, e.g. `git describe --tags --dirty`
 *         'date'    => '2026-09-15',    // any string Carbon can parse; used by @appYear
 *     ];
 *
 * Fallbacks when the config, or an individual key, is missing:
 *
 *  - `generateVersion()` returns `'unknown'`
 *  - `isDirty()` returns `true` (an unknown build is assumed not to be clean)
 *  - `raw()` returns `'n/a'`
 *  - `year()` returns the current year, so the copyright line stays sensible
 *
 * @see \Svenbw\LaravelTabler\Helpers\BladeDirectives::appVersion() for the @appVersion directive
 * @see \Svenbw\LaravelTabler\Helpers\BladeDirectives::appYear() for the @appYear directive
 */
class VersionService
{
    private ?array $versionInfo;

    public function __construct()
    {
        $versionInfo = config('version');

        $this->versionInfo = is_array($versionInfo) ? $versionInfo : null;
    }

    public static function make(): self
    {
        return new self;
    }

    public function generateVersion(): string
    {
        if ($this->versionInfo === null) {
            return 'unknown';
        }

        $version = Arr::get($this->versionInfo, 'version');
        if ($this->isDirty()) {
            $version .= '-dirty';
        }

        return $version;
    }

    public function isDirty(): bool
    {
        if ($this->versionInfo === null) {
            return true;
        }

        return Arr::get($this->versionInfo, 'dirty', false);
    }

    public function raw(): string
    {
        return Arr::get($this->versionInfo, 'raw', 'n/a');
    }

    public function year(): string
    {
        $date = Arr::get($this->versionInfo, 'date');

        if (blank($date)) {
            return (string) Carbon::now()->year;
        }

        try {
            return (string) Carbon::parse($date)->year;
        } catch (InvalidFormatException) {
            return (string) Carbon::now()->year;
        }
    }
}
